import Header from "./components/Header";
import { ThemeProviders } from "./components/ThemeProviders";
import "./globals.css";
import { Inter } from "next/font/google";
import { ReduxProviders } from "./components/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({children})=> {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProviders>
          <ThemeProviders>
            <div>
              {children}
            </div>
          </ThemeProviders>
        </ReduxProviders>
      </body>
    </html>
  );
}

export default RootLayout